services:
  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - project-network

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    networks:
      - project-network
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
    networks:
      - project-network
    depends_on:
      - backend

networks:
  project-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
